apiVersion: v1
kind: Service
metadata:
  name: {{ template "mysql.fullname" . }}-headless
  labels: {{- include "mysql.labels" . | nindent 4 }}
    component: master
  {{- if or .Values.service.annotations .Values.metrics.service.annotations }}
  annotations:
  {{- if .Values.service.annotations }}
  {{- include "mysql.tplValue" ( dict "value" .Values.service.annotations "context" $) | nindent 4 }}
  {{- end }}
  {{- if .Values.metrics.service.annotations }}
  {{- include "mysql.tplValue" ( dict "value" .Values.metrics.service.annotations "context" $) | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: mysql
  selector: {{- include "mysql.matchLabels" . | nindent 4 }}
    component: master
